In [2]:
import scipy # Biblioteca de estatisticas
from scipy import stats
import numpy as np

In [12]:
#criação dos dados que vamos utilizar
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,0,5,10]]) # Matriz de dados com 3 registros
novoUser = [8,0,2,3,0] #matriz de novos usuarios
nao_assistidos = [0,1,0,0,1] #matriz de alguns usuaris que nao asistiram o filme
print(matrix) # visualizar o array
nomeFilmes= ['Round 6',  'A Invocação do Mal','9 Desconhecidos','You' ,'La Casa de Papel'] # nome dos filmees

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [13]:
#criando um vetor com 3 posições e preencher com zero (vamos colocar os valores da similaridade entre o novoUser e cada outro usuário da matriz )
similarity =[0] * 3 # Variavel de similaridade
print(matrix[0][0])
print(matrix[1][0])
print(matrix[1,:])
#para cada usuário no sistema...
for i in range(0,3): #percorrer cada uma da linha e criar uma lista
  #vamos pegar os dados desse usuário
  temp = matrix[i,:]

  #MAS QUEREMOS APENAS COMPARAR OS DADOS QUE O NOVO USER ASSISTIU (OU SEJA... QUE NOVOUSER != 0)
  tempUser= [t for n,t in zip(novoUser,temp) if n != 0]
  tempNovoUser= [n for n in novoUser if n != 0]

  #para verificar o processo
  print('user:',i)
  print(tempUser, tempNovoUser)

  #vamos usar a biblioteca scipy.stats que ja calcula o pearson!!!
  similarity[i] = scipy.stats.pearsonr(tempUser,tempNovoUser)[0] #a função retorna dois valores e o primeiro é o coefieciente de pearson
print()

print(similarity)

8
5
[5 6 1 8 9]
user: 0
[np.int64(8), np.int64(3), np.int64(4)] [8, 2, 3]
user: 1
[np.int64(5), np.int64(1), np.int64(8)] [8, 2, 3]
user: 2
[np.int64(8), np.int64(0), np.int64(5)] [8, 2, 3]

[np.float64(0.9994237971287664), np.float64(0.23621543814299698), np.float64(0.8723686098443353)]


In [24]:
# Inicializa uma matriz de zeros para armazenar as notas ponderadas
nota_peso = np.zeros((3,5))

# Itera sobre cada usuário e cada filme
for nUser in range(3):
  for nFilme in range(5):
    # Imprime as operações que estão sendo realizadas (para depuração/visualização)
    print('nota_peso[',nUser, '][',nFilme, '] = , nao_assistidos[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')
    print('nota_peso[',nUser, '][',nFilme, '] = ', nao_assistidos[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])
    # Calcula a nota ponderada:
    # Se o filme não foi assistido pelo novo usuário (nao_assistidos[nFilme] == 1),
    # multiplica a nota do usuário atual para esse filme (matrix[nUser][nFilme])
    # pela similaridade entre o novo usuário e o usuário atual (similarity[nUser]).
    # Se o filme já foi assistido (nao_assistidos[nFilme] == 0), o resultado é 0.
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

# Imprime a matriz final de notas ponderadas
print(nota_peso)

nota_peso[ 0 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 0 ][ 0 ], * similarity[ 0 ]
nota_peso[ 0 ][ 0 ] =  1  *  5  *  0.9
nota_peso[ 0 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 0 ][ 1 ], * similarity[ 0 ]
nota_peso[ 0 ][ 1 ] =  0  *  3  *  0.9
nota_peso[ 0 ][ 2 ] = , nao_assistidos[ 2 ], * ,matrix[ 0 ][ 2 ], * similarity[ 0 ]
nota_peso[ 0 ][ 2 ] =  1  *  4  *  0.9
nota_peso[ 0 ][ 3 ] = , nao_assistidos[ 3 ], * ,matrix[ 0 ][ 3 ], * similarity[ 0 ]
nota_peso[ 0 ][ 3 ] =  1  *  0  *  0.9
nota_peso[ 0 ][ 4 ] = , nao_assistidos[ 4 ], * ,matrix[ 0 ][ 4 ], * similarity[ 0 ]
nota_peso[ 0 ][ 4 ] =  0  *  2  *  0.9
nota_peso[ 1 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 1 ][ 0 ], * similarity[ 1 ]
nota_peso[ 1 ][ 0 ] =  1  *  4  *  0.8
nota_peso[ 1 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 1 ][ 1 ], * similarity[ 1 ]
nota_peso[ 1 ][ 1 ] =  0  *  0  *  0.8
nota_peso[ 1 ][ 2 ] = , nao_assistidos[ 2 ], * ,matrix[ 1 ][ 2 ], * similarity[ 1 ]
nota_peso[ 1 ][ 2 ] =  1  *  5  *  0.8
nota_peso[ 1 ][ 

In [15]:
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas)

[ 0.          1.41729263  0.          0.         16.84616782]


In [16]:
import numpy as np

# Filmes não assistidos (0 = já assistiu, 1 = não assistiu)
nao_assistidos = [1, 0, 1, 1, 0]   # usuário só não assistiu filmes 0, 2 e 3

# Matriz de notas dos usuários (3 usuários x 5 filmes)
# Cada linha = um usuário, cada coluna = um filme
matrix = [
    [5, 3, 4, 0, 2],   # usuário 0
    [4, 0, 5, 3, 1],   # usuário 1
    [2, 4, 0, 5, 3]    # usuário 2
]

# Similaridade de cada usuário em relação ao "usuário alvo"
similarity = [0.9, 0.8, 0.6]

# Cria a matriz de pesos (3 usuários x 5 filmes)
nota_peso = np.zeros((3,5))

for nUser in range(3):
    for nFilme in range(5):
        print(f'nota_peso[{nUser}][{nFilme}] = nao_assistidos[{nFilme}] * matrix[{nUser}][{nFilme}] * similarity[{nUser}]')
        print(f'nota_peso[{nUser}][{nFilme}] = {nao_assistidos[nFilme]} * {matrix[nUser][nFilme]} * {similarity[nUser]}')

        nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

print("\nMatriz final de nota_peso:")
print(nota_peso)

nota_peso[0][0] = nao_assistidos[0] * matrix[0][0] * similarity[0]
nota_peso[0][0] = 1 * 5 * 0.9
nota_peso[0][1] = nao_assistidos[1] * matrix[0][1] * similarity[0]
nota_peso[0][1] = 0 * 3 * 0.9
nota_peso[0][2] = nao_assistidos[2] * matrix[0][2] * similarity[0]
nota_peso[0][2] = 1 * 4 * 0.9
nota_peso[0][3] = nao_assistidos[3] * matrix[0][3] * similarity[0]
nota_peso[0][3] = 1 * 0 * 0.9
nota_peso[0][4] = nao_assistidos[4] * matrix[0][4] * similarity[0]
nota_peso[0][4] = 0 * 2 * 0.9
nota_peso[1][0] = nao_assistidos[0] * matrix[1][0] * similarity[1]
nota_peso[1][0] = 1 * 4 * 0.8
nota_peso[1][1] = nao_assistidos[1] * matrix[1][1] * similarity[1]
nota_peso[1][1] = 0 * 0 * 0.8
nota_peso[1][2] = nao_assistidos[2] * matrix[1][2] * similarity[1]
nota_peso[1][2] = 1 * 5 * 0.8
nota_peso[1][3] = nao_assistidos[3] * matrix[1][3] * similarity[1]
nota_peso[1][3] = 1 * 3 * 0.8
nota_peso[1][4] = nao_assistidos[4] * matrix[1][4] * similarity[1]
nota_peso[1][4] = 0 * 1 * 0.8
nota_peso[2][0] = nao_assistid

In [17]:
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas)

[8.9 0.  7.6 5.4 0. ]


In [20]:
# Cria uma cópia temporária da matriz de pesos
temp_peso = nota_peso
# Substitui os valores maiores que 0 por 1 (indicando filmes que contribuíram para a nota ponderada)
temp_peso[nota_peso > 0] = 1
print(temp_peso)

# Cria uma matriz temporária para armazenar a similaridade ponderada
temp_similaridade = np.zeros((3,5))
# Calcula a similaridade ponderada para cada filme e usuário
for nUser in range(3):
  for nFilme in range(5):
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]

print(temp_similaridade)

# Acumula a similaridade ponderada por filme
similaridade_acumulada = np.sum(temp_similaridade.T,axis=1)
print(similaridade_acumulada)

[[1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]]
[[0.9 0.  0.9 0.  0. ]
 [0.8 0.  0.8 0.8 0. ]
 [0.6 0.  0.  0.6 0. ]]
[2.3 0.  1.7 1.4 0. ]


In [21]:
nota_final =[0] * 5
#agora a normalização para cada filme com nota acumulada, eu normalizo pela soma dos pesos (similaridade)
for nFilme in range(5):
  if(similaridade_acumulada[nFilme] > 0):
    nota_final[nFilme] =  notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
  else:
    nota_final[nFilme] = 0

print(nota_final)

[np.float64(3.869565217391304), 0, np.float64(4.470588235294117), np.float64(3.8571428571428577), 0]


In [22]:
# Calcula o número de filmes não assistidos
nAssistidos = sum(nao_assistidos)

# Obtém os índices dos filmes não assistidos mais bem avaliados
# Classifica os índices com base nas notas finais calculadas em ordem decrescente
# Seleciona os 'nAssistidos' principais índices
notasOrdenadasIndex = sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]

# Imprime os índices dos filmes recomendados
print(notasOrdenadasIndex)

# Itera pelos índices dos filmes recomendados e imprime o nome do filme e a nota
for i in notasOrdenadasIndex:
  print(nomeFilmes[i], 'nota: ', nota_final[i])

[2, 0, 3]
9 Desconhecidos nota:  4.470588235294117
Round 6 nota:  3.869565217391304
You nota:  3.8571428571428577
